<?php
$lang = array( 
'news_error' => 'Error',
'news_error_ruffian' => 'A ruffian that will swear, drink, dance, revel the night, rob, murder and commit the oldest of ins the newest kind of ways.',
'news_success' => 'Success',
'news_del_invalid' => 'Invalid ID.',
'news_del_confirm' => 'Confirm Delete',
'news_del_click' => 'Do you really want to delete this news entry? Click ',
'news_del_here' => 'here',
'news_del_if' => 'if you are sure.',
'news_del_what' => 'what are you doing?',
'news_del_redir' => 'News entry deleted - Please wait while you are redirected!',
'news_del_stdhead' => 'News',
'news_add_item' => 'The news item cannot be empty!',
'news_add_title' => 'The news title cannot be empty!',
'news_add_success' => 'News entry was added successfully.',
'news_add_oopss' => 'oopss',
'news_add_something' => 'Something\'s wrong !! .',
'news_edit_invalid' => 'Invalid news item ID.',
'news_edit_nonews' => 'No news item with that ID .',
'news_edit_body' => 'Body cannot be empty!',
'news_edit_title' => 'Title cannot be empty!',
'news_edit_success' => 'News item was edited successfully - Please wait while you are redirected!',
'news_edit_item' => 'Edit News Item',
'news_submit_new' => 'Submit News Item',
'news_sticky' => 'Sticky',
'news_yes' => 'Yes',
'news_no' => 'No',
'news_anonymous' => 'Anonymous',
'news_okay' => 'Okay',
'news_created_by' => '.&nbsp;News&nbsp;entry&nbsp;created&nbsp;by&nbsp',
'news_edit' => 'Edit',
'news_delete' => 'Delete',
'news_stdhead' => 'News Page'
);
?>