<?php
$lang = array(
#Browse
'browse_error' => "שגיאה",
'browse_invalid_cat' => "מספר קטגוריה שגוי.",
'browse_search' => "תוצאות חיפוש עבור ",
'browse_show_all' => "הצגת הכל",
'browse_active' => "פעיל",
'browse_inc_dead' => "כולל לא פעילים",
'browse_dead' => "רק לא פעילים",
'browse_go' => "חיפוש!",
'browse_search' => "תוצאות חיפוש עבור ",
'browse_not_found' => "לא נמצא דבר!",
'browse_tryagain' => "נסו שוב עם שינוי טקסט.",//Try again with a refined search string.
'browse_nothing' => "אין פה כלום!",//"Nothing here!",
'browse_sorry' => "מצטערים :",
'browse_search_btn' => "חיפוש!",
'browse_all_types' => "(כל הסוגים)",
'browse_search' => "חיפוש עבור טורנטים:",
'browse_search_in' => "בתוך:",
'browse_search_by' => "על ידי:",
'browse_only_free' => "<span style='font-weight:bold;color:#006600'>הורדה חופשית</span>",
'browse_topdownloaded' => "<span style='font-weight:bold;color:#D81313'>הכי מורדים</span>",
'browse_latest'        => "טורנטים אחרונים",
#latest torrents
'latesttorrents_title' => $TBDEV['latest_torrents_limit']." טורנטים חארונים",
'latesttorrents_type' => "סוג",
'latesttorrents_name' => "שם",
'latesttorrents_seeders' => "משתפים",
'latesttorrents_leechers' => "מורידים",
'latesttorrents_no_torrents' => "לא נמצאו טורנטים",
# last 5
'last5torrents_title' => "5 טורנטים האחרונים",
'last5torrents_type' => "סוג",
'last5torrents_name' => "שם",
'last5torrents_dl'    => "הורד",
'last5torrents_snatched' => "הורדות",
'last5torrents_seeders' => "שיתוף",
'last5torrents_leechers' => "הורדה",
'last5torrents_no_torrents' => "לא נמצאו טורנטים",
# top 5
'top5torrents_title' => " 5 טורנטים הגדולים",
'top5torrents_type' => "סוג",
'top5torrents_name' => "שם",
'top5torrents_dl'    => "הורד",
'top5torrents_snatched' => "הורדות",
'top5torrents_seeders' => "מהירות",
'top5torrents_leechers' => "הורדה",
'top5torrents_no_torrents' => "לא נמצאו טורנטים",
//global show hide
'browse_hide_show' => "[הסתרה/הצגה]",
'browse_click_more' => "לחץ לעוד פרטים",
'browse_cats_open' => "פתיחה",
'browse_cats_close' => "סגירה",
);
?>