<?php
$lang = array(
'upload_sorry' => "Sorry...",
'upload_no_auth' => "You are not authorized to upload torrents!",
'upload_announce_url' => "The tracker's announce url is",
'upload_delete' => "Delete",
'upload_torrent' => "Torrent file",
'upload_name' => "Torrent name",
'upload_filename' => "Taken from filename if not specified. <b>Please use descriptive names.</b>",
'upload_nfo' => "NFO file",
'upload_nfo_info' => "<b>Optional.</b> Can only be viewed by power users.",
'upload_description1' => "Description",
'upload_html_bbcode' => "HTML is <b>not</b> allowed.",
'upload_choose_one' => "choose one",
'upload_type' => "Type",
'upload_format' => "Format",
'upload_submit' => "Do it!",
'upload_poster' => "Poster",
'upload_poster1' => "Direct link for a poster image to be shown on the details page",
'upload_anonymous' => "Anonymous Uploader",
'upload_anonymous1' => "Don't show my username in 'Uploaded By' field in browse.",
'upload_description' => "Genre",
'upload_small_descr' => "Genre for the uploaded file. Check http://anidb.net",
'upload_image' => "Screenshot",
'upload_image_info' => "Use this to upload images from the file. Only .bmp, .gif, .jpg images allowed.",
'upload_tube' => "Trailer",
'upload_tube_notice' => "Should be in the format of <a href='http://www.youtube.com/watch?v=TYxbGgeeVmI'>http://www.youtube.com/watch?v=TYxbGgeeVmI</a>",
'upload_imdb_url' => "IMDB Url",
'upload_imdb_tfi' => "Taken from Imdb - ",
'upload_imdb_rfmo' => "Add the IMDB url to display IMDB data on details.",
'upload_strip_ascii' => "Strip ASCII",
'upload_request' => "Request",
'upload_request_info' => "If you are filling a request please select it here so interested members can be notified!",
'upload_request_no' => "No requests available",
'upload_request_not' => "(choose one if needed)",
'upload_stdhead' => "Upload",
);

?>