<?php
$lang = array(
'upload_sorry' => "מצטערים...",
'upload_no_auth' => "אין באפשרותך להעלות טורנטים!",
'upload_announce_url' => "כתובת announce היא",
'upload_delete' => "הסרה",
'upload_torrent' => "קובץ Torrent",
'upload_name' => "שם Torrent",
'upload_filename' => "Taken from filename if not specified. <b>Please use descriptive names.</b>",
'upload_nfo' => "קובץ NFO",
'upload_nfo_info' => "<b>אפשרי.</b> נצפה על ידי משתמשי על בלבד.",
'upload_description1' => "תאור",
'upload_html_bbcode' => "הוא HTML <b>לא</b> מאושר.",
'upload_choose_one' => "בחירת אחד",
'upload_type' => "סוג",
'upload_format' => "פורמט",
'upload_submit' => "ביצוע!",
'upload_poster' => "פוסטר",
'upload_poster1' => "Direct link for a poster image to be shown on the details page",
'upload_anonymous' => "מעלה אנונימי",
'upload_anonymous1' => "אל תציג את שמי ב 'הועלה אל ידי' בדף הטורנטים.",
'upload_description' => "ג'אנר",
'upload_small_descr' => "ג'אנט עבור קובץ המועלה. בדיקה באתר http://anidb.net",
'upload_image' => "תמונת מסך",
'upload_image_info' => "Use this to upload images from the file. Only .bmp, .gif, .jpg images allowed.",
'upload_tube' => "טריילר",
'upload_tube_notice' => "Should be in the format of <a href='http://www.youtube.com/watch?v=TYxbGgeeVmI'>http://www.youtube.com/watch?v=TYxbGgeeVmI</a>",
'upload_imdb_url' => "כתובת IMDB",
'upload_imdb_tfi' => "נלקח מאתר Imdb - ",
'upload_imdb_rfmo' => "הוספת כתובת IMDB יצירת את המידע מאתר IMDB.",
'upload_strip_ascii' => "Strip ASCII",
'upload_request' => "בקשה",
'upload_request_info' => "אם הנך מבצע בקשה נא לבחור מן הרשימה!",
'upload_request_no' => "אין בקשות",
'upload_request_not' => "(נא לבחור אחד לפי הצורך)",
'upload_stdhead' => "העלאה",
);

?>