<?php
$lang = array(
#Browse
'browse_error' => "Error",
'browse_invalid_cat' => "Invalid category ID.",
'browse_search' => "Search results for ",
'browse_show_all' => "Show all",
'browse_active' => "active",
'browse_inc_dead' => "including dead",
'browse_dead' => "only dead",
'browse_go' => "Go!",
'browse_search' => "Search results for ",
'browse_not_found' => "Nothing found!",
'browse_tryagain' => "Try again with a refined search string.",
'browse_nothing' => "Nothing here!",
'browse_sorry' => "Sorry pal :",
'browse_search_btn' => "Search!",
'browse_all_types' => "(all types)",
'browse_search' => "Search for torrents:",
'browse_search_in' => "in:",
'browse_search_by' => "by:",
'browse_only_free' => "<span style='font-weight:bold;color:#006600'>Free Torrents</span>",
'browse_topdownloaded' => "<span style='font-weight:bold;color:#D81313'>Top Downloaded</span>",
'browse_latest'        => "Latest Torrents",
#latest torrents
'latesttorrents_title' => $TBDEV['latest_torrents_limit']." latest torrents",
'latesttorrents_type' => "Type",
'latesttorrents_name' => "Name",
'latesttorrents_seeders' => "Seeders",
'latesttorrents_leechers' => "Leechers",
'latesttorrents_no_torrents' => "No torrents Found",
# last 5
'last5torrents_title' => "Last 5 torrents",
'last5torrents_type' => "Type",
'last5torrents_name' => "Name",
'last5torrents_dl'    => "DL",
'last5torrents_snatched' => "DLs",
'last5torrents_seeders' => "Seed",
'last5torrents_leechers' => "Leech",
'last5torrents_no_torrents' => "No torrents Found",
# top 5
'top5torrents_title' => " Top 5 torrents",
'top5torrents_type' => "Type",
'top5torrents_name' => "Name",
'top5torrents_dl'    => "DL",
'top5torrents_snatched' => "DLs",
'top5torrents_seeders' => "Seed",
'top5torrents_leechers' => "Leech",
'top5torrents_no_torrents' => "No torrents Found",
//global show hide
'browse_hide_show' => "[Hide/Show]",
'browse_click_more' => "Click for more info",
'browse_cats_open' => "Open",
'browse_cats_close' => "Close",
);
?>