<?php

$lang = array(

#my gets
'my_updated' => 'Profile updated',
'my_mail_sent' => 'Confirmation email has been sent',
'my_emailch' => 'Email address changed',
'my_delete' => 'Delete',

#my header
'my_logout' => 'Logout',
'my_torrents' => 'My torrents',
'my_users_lists' => 'My users lists',
'my_edit_torrents' => 'View/Edit your Torrents',
'my_edit_friends' => 'View/Edit your Friends',
'my_search' => 'Search Members',

#my options
'my_none' => 'None selected',
'my_accept_pm' => 'Accept PMs',
'my_except_blocks' => 'All (except blocks)',
'my_only_friends' => 'Friends only',
'my_only_staff' => 'Staff only',
'my_delete_pms' => 'Delete PMs',
'my_yes' => 'Yes',
'my_default_delete' => '(Default value for "Delete PM on reply")',
'my_save_pms' => 'Save PMs',
'my_default_save' => '(Default value for "Save PM to Sentbox")',
'my_email_notif' => 'Email notification',
'my_notify_pm' => 'Notify me when I have received a PM',
'my_notify_torrent' => 'Notify me when a torrent is uploaded in one of my default browsing categories.',
'my_browse' => 'Browse default categories',
'my_stylesheet' => 'Stylesheet',
'my_language' => 'Language',
'my_country' => 'Country',
'my_tz' => 'Timezone',
'my_checkdst' => 'Daylight Saving',
'my_auto_dst' => 'Auto correct DST?',
'my_is_dst' => 'Is daylight saving time in effect?',
'my_avatar' => 'Avatar URL',
'my_avatar_info' => 'Width should be 150 pixels (will be resized if necessary)<br />If you need a host for the picture, try the <a href="bitbucket-upload.php">bitbucket</a>.',
'my_tor_perpage' => 'Torrents per page',
'my_default' => '(0=use default setting)',
'my_top_perpage' => 'Topics per page',
'my_post_perpage' => 'Posts per page',
'my_view_avatars' => 'View avatars',
'my_low_bw' => '(Low bandwidth users might want to turn this off)',
'my_info' => 'Info',
'my_tags' => 'Displayed on your public page. May contain <a href="tags.php" target="_blank">BB codes</a>.',
'my_email' => 'Email address',
'my_email_pass' => 'Please enter your password if changing your email address!',
'my_note' => '<b>Note:</b> In order to change your email address, you will receive another<br />confirmation email to your new address.',
'my_chpass' => 'Change password',
'my_pass_again' => 'Type password again',
'my_submit' => 'Submit changes!',
'my_revert' => 'Revert changes!',
'my_acc_parked' => 'Account parked',
'my_acc_parked_message' => 'You can park your account to prevent it from being deleted because of inactivity if you go away on for example a vacation.',
'my_acc_parked_message1' => 'When the account has been parked limits are put on the account, for example you cannot use the tracker and browse some of the pages.',
'my_none_select' => '---- None selected ----',
'my_q1' => 'Mother\'s birthplace',
'my_q2' => 'Best childhood friend',
'my_q3' => 'Name of first pet',
'my_q4' => 'Favorite teacher',
'my_q5' => 'Favorite historical person',
'my_q6' => 'Grandfather\'s occupation',
'my_question' => 'Question',
'my_sec_answer' => 'Secret answer',
'my_gender' => 'Gender',
'my_male' => 'Male',
'my_female' => 'Female',
'my_na' => 'Unknown',
'my_hideprofile' => 'Hide Profile',
'my_default_hideprofile' => '(Hidden Status - If this is checked Your profile is protected!)',
'my_forum_subscribe' => 'Subscribe Forum PM',
'my_split' => 'Split Torrents by Days',  
'my_no_avatar_allow' => 'Avatar changing disabled!',
'my_view_hentai_torrents' => 'View Hentai Torrents',
'my_shoutback' => 'Shoutbox Background',
'my_shoutback_transparent_white' => 'Transparent(Light Theme)',
'my_shoutback_grey' => 'Grey',
'my_shoutback_transparent_black' => 'Transparent(Dark Theme)',
'my_top_moods' => "Top Moods",
'my_clearnewtagmanually' => 'Manually Clear New Tag',
'my_default_clearnewtagmanually' => 'Check to manual clear new tag, un-check to auto clean new tag',
'my_view_xxx' => 'View XXX Torrents',
'my_view_xxx_body'  => 'Check to make XXX Torrents visible on browse page.',
'my_passkey_ip' => 'This option can prevent unauthorized downloading through your passkey by linking it to your IP address. If you have dynamic IP address, do NOT turn this option on.',
'my_passkey_ip_ip' => 'Current IP address: ',
'my_yes' => 'Yes',
'my_no' => 'No',
'my_cpm' => "When any of your uploaded torrents are commented on, you will be PMed.",
'my_pm_cpm' => 'Torrent Comment Notification',

#my stdhead
'my_stdhead' => '\'s private page'
);

?>