<?php

$lang = array(

#Details
'details_user_error' => "שגיאת משתמש",
'details_bad_id' => "ID שגוי",
'details_error' => "שגיאה",
'details_torrent_id' => "ID שגוי לטורנט.",
'details_success' => "הועלה בהצלחה!",
'details_start_seeding' => "יש באפשרותך לשתף כעת. <b>Note</b> הטורנט יהיה במצב בלתי נראה עד שתבצעו זאת!",
'details_success_edit' => "נערך בהצלחה!",
'details_go_back' => "חזרה אל ",
'details_whence' => "whence you came",
'details_rating_added' => "דירוג נוסף!",
'details_download' => "הורדה",
'details_info_hash' => "Info hash",
'details_description' => "תאור",
'details_nfo' => "NFO",
'details_view_nfo' => "צפיה NFO",
'details_visible' => "נראה",
'details_no' => "לא",
'details_dead' => " (לא פעיל)",
'details_banned' => "מושעה",
'details_type' => "סוג",
'details_format' => "פורמט",
'details_selected' => "(לא נבחרו)",
'details_last_seeder' => "משתף&nbsp;אחרון",
'details_last_activity' => "פעילות אחרונה ",
'details_size' => "גודל",
'details_bytes' => "בייטים ",
'details_added' => "נוסף",
'details_long' => "ארוך",
'details_views' => "צפיות",
'details_hits' => "לחיצות",
'details_snatched' => "הורדות",
'details_times' => "(ים)פעם",
'details_unknown' => "לא ידוע",
'details_edit' => "[עריכת טורנט זה]",
'details_num_files' => "מספר קבצים",
'details_list' => "[צפיה ברשימה המלאה]",
'details_files' => " קבצים",
'details_peers' => "משתפים",
'details_peer_total' => " משתפים סך הכל",
'details_comments' => "תגובות עבור ",
'details_add_comment' => "הוספת תגובה",
'details_no_comment' => "אין תגובות כרגע!",
'details_details' => "פרטים עבור טורנט ",
'details_report' => 'דיווח טורנט',
'details_report1' => 'עבור עבירה על חוקים',//'for breaking the rules',
'details_small_descr' => "ג'אנר",
'details_dloadpos' => "<strong><font color='#FF0000'>אין ברשותך מספיק נקודות שיתוף להורדה או שאפשרויות ההורדה שלך מבוטלות!</font></strong>",
'details_banned_clients'=> 'תוכנות מושעות',
'details_clear_clientbans' => 'לחצו כאן בכדי לבטל השעיית תוכנה', 
'details_thanks' => "רשימת תודות",
'details_thanks_no' =>"לא נאמר תודה עדיין!",
'details_thanks_say' => "תודות!",
'details_thanks_added' => "תודה נוסף!",
'details_reseed' => "בקשת שיתוף מחדש",
'details_similiar' => 'טורנטים דומים',
'details_none' => 'ללא',
'details_poster' => "פוסטר",
'details_health'  => "רמת חיי טורנט",
'details_imdb_url'  => "iMDB קישור",
'details_youtube' => 'טריילר',
'details_youtube_link' => 'פתיחה בחלון חדש',
);
?>