<?php
$lang = array(
#Modtask
'modtask_user_error' => "USER ERROR",
'modtask_try_again' => "Please try again",
'modtask_error' => "Error",
'modtask_bad_id' => "Bad user ID.",
'modtask_promoted' => "Promoted",
'modtask_demoted' => "Demoted",
'modtask_have_been' => "You have been %s to",
'modtask_by' => "by",
'modtask_warned' => " - Warning removed by ",
'modtask_warned_removed' => "Your warning has been removed by ",
'modtask_warned_by' => " - Warned by ",
'modtask_reason' => "Reason:",
'modtask_warning_received' => "You have received a warning from ",
'modtask_week' => " week",
'modtask_warning_duration' => "You have received a %s warning from ",
'modtask_warned_for' => " - Warned for %s by ",
'modtask_donor_removed' => " - Donor status removed by ",
'modtask_donor_expired' => "Your donator status has expired.",
'modtask_donor_set' => " - Donor status set by ",
'modtask_received_donor' => "You have received donor status from ",
'modtask_donor_duration' => "You have received donator status for %s from ",
'modtask_donor_for' => " - Donator status set for %s by ",
'modtask_enabled' => "- Enabled by ",
'modtask_disabled' => "- Disabled by ",
'modtask_custom_title' => " - Custom Title changed to ",
'modtask_custom_email' => " - Email changed to ",
'modtask_passkey' => " - Passkey ",
'modtask_reset' => " Reset to ",
'modtask_not_image' => "Not an image or unsupported image!",
'modtask_image_small' => "Image is too small",
'modtask_avatar_change' => " - Avatar changed from ",
'modtask_to' => "to",
'modtask_no_idea' => "No idea what to do",
'modtask_fls' => "Added to First line Support by ",
'modtask_fls1' => "You have been added to First line Support by ",
'modtask_fls2' => "Removed from First line Support by ",
'modtask_fls3' => "You have been removed from First line Support by ",
'modtask_fls4' => "probably because you where inactive or asked to be removed",
'modtask_subtract_download' => " - Subtracted Download",
'modtask_added_download' => " - Added Download",
'modtask_add_upload' => " - Added Upload",
'modtask_subtract_upload' => " - Subtracted Upload",
'modtask_chatpos' => "- Chat post rights set to",
'modtask_games_dis_by' => " - Gaming disablement by ",
'modtask_games_dis_right' => "Your gaming rights have been disabled by ",
'modtask_games_dis_status' => " - Gaming disablement status removed by ",
'modtask_games_res_by' => "Your gaming rights have been restored by ",
'modtask_games_dis_from' => "games disablement from ",
'modtask_games_dis_for' => " - Games disablement for",
'modtask_games_disabled' => "Games disabled  = ",
'modtask_games_poss_yes' => "Games possible = Yes",
'modtask_games_poss_no' => "Games possible = No",
'modtask_gl_notification' => "Notification!",
'modtask_gl_reason' => "Reason:",
'modtask_gl_received' => "You have received",
'modtask_gl_by' => " by ",
'modtask_gl_week' => " week",
'modtask_gl_weeks' => "s",
'modtask_gl_from' => " from ",
'modtask_to' => " to ",
'modtask_gl_was' => ". was ",
'modtask_to' => "to",
);
?>