<?php

$lang = array(

#Details
'details_user_error' => "USER ERROR",
'details_bad_id' => "Bad ID",
'details_error' => "Error",
'details_torrent_id' => "No torrent with ID.",
'details_success' => "Successfully uploaded!",
'details_start_seeding' => "You can start seeding now. <b>Note</b> that the torrent won't be visible until you do that!",
'details_success_edit' => "Successfully edited!",
'details_go_back' => "Go back to ",
'details_whence' => "whence you came",
'details_rating_added' => "Rating added!",
'details_download' => "Download",
'details_info_hash' => "Info hash",
'details_description' => "Description",
'details_nfo' => "NFO",
'details_view_nfo' => "View NFO",
'details_visible' => "Visible",
'details_no' => "no",
'details_dead' => " (dead)",
'details_banned' => "Banned",
'details_type' => "Type",
'details_format' => "Format",
'details_selected' => "(none selected)",
'details_last_seeder' => "Last&nbsp;seeder",
'details_last_activity' => "Last Activity ",
'details_size' => "Size",
'details_bytes' => "bytes ",
'details_added' => "Added",
'details_long' => "LONG",
'details_views' => "Views",
'details_hits' => "Hits",
'details_snatched' => "Snatched",
'details_times' => "time(s)",
'details_unknown' => "unknown",
'details_edit' => "[Edit this torrent]",
'details_num_files' => "Num Files",
'details_list' => "[see full list]",
'details_files' => " files",
'details_peers' => "Peers",
'details_peer_total' => " peer(s) total",
'details_comments' => "Comments for ",
'details_add_comment' => "Add a Comment",
'details_no_comment' => "No Comments yet!",
'details_details' => "Details for torrent ",
'details_report' => 'Report torrent',
'details_report1' => 'for breaking the rules',
'details_small_descr' => "Genre",
'details_dloadpos' => "<strong><font color='#FF0000'>You don't have enough seedpoints to download OR your download rights have been disabled!</font></strong>",
'details_banned_clients'=> 'Banned Clients',
'details_clear_clientbans' => 'Click Here to remove client bans', 
'details_thanks' => "Thanks list",
'details_thanks_no' =>"Nobody said thanks!",
'details_thanks_say' => "Thanks!",
'details_thanks_added' => "Thanks added!",
'details_reseed' => "Request reseed",
'details_similiar' => 'Similiar torrents',
'details_none' => 'None',
'details_poster' => "Poster",
'details_health'  => "Torrent Health",
'details_imdb_url'  => "iMDB Link",
'details_youtube' => 'Trailer',
'details_youtube_link' => 'Open in a new window',
);
?>